# Generated by Django 5.1.2 on 2024-11-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password1',
            new_name='pass1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password2',
            new_name='pass2',
        ),
    ]
